import { CATEGORY_MAP } from '@/types';
import type { Product, CategoryMeta, CategorySlug } from '@/types';

export const CATEGORIES: CategoryMeta[] = [
  {
    name: CATEGORY_MAP.productivity,
    slug: 'productivity',
    description: 'Tools to streamline workflows, manage tasks, and keep teams aligned.',
    color: '#6366f1',
    icon: '⚡',
  },
  {
    name: CATEGORY_MAP.devtools,
    slug: 'devtools',
    description: 'Developer infrastructure, CI/CD, monitoring, and code quality tools.',
    color: '#0ea5e9',
    icon: '🛠',
  },
  {
    name: CATEGORY_MAP.analytics,
    slug: 'analytics',
    description: 'Data pipelines, dashboards, and business intelligence platforms.',
    color: '#f59e0b',
    icon: '📊',
  },
  {
    name: CATEGORY_MAP.crm,
    slug: 'crm',
    description: 'Customer relationship management, sales automation, and support tools.',
    color: '#10b981',
    icon: '🤝',
  },
];

export const PRODUCTS: Product[] = [
  // ── Productivity ─────────────────────────────────────────────────────────
  {
    id: 'p-1',
    slug: 'flowdesk',
    name: 'FlowDesk',
    tagline: 'Project management built for fast-moving teams.',
    description:
      'FlowDesk brings together task tracking, sprint planning, and real-time collaboration into a single, opinionated workspace. Designed for software teams that move fast and ship often, FlowDesk cuts meeting overhead with async-first features like threaded updates, automated standup digests, and Git-integrated task states.',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['project-management', 'sprint-planning', 'async', 'git-integration'],
    logoPlaceholder: { initials: 'FD', color: '#6366f1' },
    featured: true,
    rating: 4.7,
    reviewCount: 1284,
    website: 'https://example.com/flowdesk',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Great for small teams just getting started.',
        features: ['Up to 5 members', '10 active projects', 'Basic integrations', '1 GB storage'],
        cta: 'Get started free',
      },
      {
        name: 'Pro',
        price: 18,
        billingPeriod: 'month',
        description: 'Everything a growing team needs.',
        features: [
          'Unlimited members',
          'Unlimited projects',
          'Advanced integrations',
          '50 GB storage',
          'Priority support',
          'Custom workflows',
        ],
        cta: 'Start Pro trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'For large organizations with advanced requirements.',
        features: [
          'SSO & SAML',
          'Audit logs',
          'Dedicated CSM',
          'Custom SLAs',
          'Unlimited storage',
          'On-premise option',
        ],
        cta: 'Contact sales',
      },
    ],
  },
  {
    id: 'p-2',
    slug: 'notionflow',
    name: 'NotionFlow',
    tagline: 'Turn your docs into living workflows.',
    description:
      'NotionFlow bridges the gap between documentation and execution. Teams can create rich documents that contain embedded tasks, approval flows, and real-time data from connected tools. Stop copy-pasting between wikis and task trackers — your documentation is your workflow.',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['documentation', 'workflow', 'wiki', 'collaboration'],
    logoPlaceholder: { initials: 'NF', color: '#818cf8' },
    featured: true,
    rating: 4.5,
    reviewCount: 879,
    website: 'https://example.com/notionflow',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'For individuals and tiny teams.',
        features: ['1 workspace', '5 members', 'Unlimited docs', 'Basic blocks'],
        cta: 'Start for free',
      },
      {
        name: 'Pro',
        price: 12,
        billingPeriod: 'month',
        description: 'Unlock the full power of NotionFlow.',
        features: [
          'Unlimited workspaces',
          'Unlimited members',
          'Version history',
          'API access',
          'Custom templates',
        ],
        cta: 'Start Pro trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Enterprise-grade security and compliance.',
        features: ['SSO', 'SCIM provisioning', 'Compliance exports', 'Dedicated support'],
        cta: 'Talk to sales',
      },
    ],
  },
  {
    id: 'p-3',
    slug: 'calstack',
    name: 'CalStack',
    tagline: 'Smart scheduling for distributed teams.',
    description:
      'CalStack solves the coordination nightmare of distributed teams across time zones. Its AI layer suggests optimal meeting times, automatically tracks meeting fatigue, and integrates with Google, Outlook, and Zoom. Features a no-meeting-day policy enforcer loved by engineering leaders.',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['scheduling', 'calendar', 'async', 'distributed-teams'],
    logoPlaceholder: { initials: 'CS', color: '#a5b4fc' },
    featured: true,
    rating: 4.3,
    reviewCount: 562,
    website: 'https://example.com/calstack',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Basic scheduling for small teams.',
        features: ['3 users', '1 calendar integration', 'Basic scheduling'],
        cta: 'Start free',
      },
      {
        name: 'Pro',
        price: 9,
        billingPeriod: 'month',
        description: 'AI-powered scheduling for teams.',
        features: [
          'Unlimited users',
          'All calendar integrations',
          'AI time suggestions',
          'Meeting analytics',
          'Fatigue tracking',
        ],
        cta: 'Try Pro free',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'For large distributed organizations.',
        features: ['HRIS integration', 'Admin dashboard', 'Custom policies', 'SLA support'],
        cta: 'Contact sales',
      },
    ],
  },
  {
    id: 'p-4',
    slug: 'slipbox',
    name: 'Slipbox',
    tagline: 'Knowledge management that actually sticks.',
    description:
      'Slipbox is a second-brain tool designed for knowledge workers who need to connect ideas across projects, clients, and time. Inspired by Zettelkasten methodology, it surfaces connections you didn\'t know existed and prevents siloed information from getting lost in scattered notes.',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['knowledge-management', 'notes', 'zettelkasten', 'PKM'],
    logoPlaceholder: { initials: 'SB', color: '#c7d2fe' },
    featured: false,
    rating: 4.6,
    reviewCount: 443,
    website: 'https://example.com/slipbox',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Personal knowledge management, free forever.',
        features: ['1 user', 'Up to 500 notes', 'Graph view', 'Export to Markdown'],
        cta: 'Get started',
      },
      {
        name: 'Pro',
        price: 8,
        billingPeriod: 'month',
        description: 'Unlimited notes and team sharing.',
        features: ['Unlimited notes', 'Team sharing', 'Version history', 'AI connections', 'API'],
        cta: 'Go Pro',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Org-wide knowledge graph.',
        features: ['SSO', 'Admin controls', 'Compliance', 'Dedicated onboarding'],
        cta: 'Talk to sales',
      },
    ],
  },

  // ── DevTools ──────────────────────────────────────────────────────────────
  {
    id: 'd-1',
    slug: 'pipeforge',
    name: 'PipeForge',
    tagline: 'CI/CD pipelines that deploy in seconds, not minutes.',
    description:
      'PipeForge is a next-generation CI/CD platform built on distributed build runners and aggressive caching. Teams report 60–80% faster build times out of the box. It integrates natively with GitHub, GitLab, and Bitbucket, and ships with pre-built pipeline templates for 40+ popular stacks.',
    category: 'DevTools',
    categorySlug: 'devtools',
    tags: ['ci-cd', 'devops', 'pipelines', 'deployment'],
    logoPlaceholder: { initials: 'PF', color: '#0ea5e9' },
    featured: true,
    rating: 4.8,
    reviewCount: 2107,
    website: 'https://example.com/pipeforge',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Open-source projects and hobby use.',
        features: ['3 concurrent builds', '500 build minutes/mo', 'Public repos only', '2 pipelines'],
        cta: 'Start free',
      },
      {
        name: 'Pro',
        price: 49,
        billingPeriod: 'month',
        description: 'For professional teams shipping production software.',
        features: [
          'Unlimited concurrent builds',
          '5,000 build minutes/mo',
          'Private repos',
          'Caching & artifacts',
          'Slack notifications',
          'Priority queue',
        ],
        cta: 'Start 14-day trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Self-hosted or dedicated cloud with SLA guarantees.',
        features: [
          'Unlimited build minutes',
          'Self-hosted runners',
          'IP allowlisting',
          'SAML SSO',
          'Compliance reports',
          '99.99% SLA',
        ],
        cta: 'Contact sales',
      },
    ],
  },
  {
    id: 'd-2',
    slug: 'logpilot',
    name: 'LogPilot',
    tagline: 'Observability without the setup tax.',
    description:
      'LogPilot is an all-in-one observability platform that unifies logs, metrics, and traces. Unlike legacy APM tools, LogPilot requires no agents — just point your SDK at the endpoint. Its smart anomaly detection surfaces issues before they page your on-call team.',
    category: 'DevTools',
    categorySlug: 'devtools',
    tags: ['observability', 'logging', 'APM', 'monitoring', 'tracing'],
    logoPlaceholder: { initials: 'LP', color: '#38bdf8' },
    featured: true,
    rating: 4.6,
    reviewCount: 934,
    website: 'https://example.com/logpilot',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Basic observability for indie developers.',
        features: ['1 service', '3-day log retention', '10k events/day', 'Email alerts'],
        cta: 'Start free',
      },
      {
        name: 'Pro',
        price: 79,
        billingPeriod: 'month',
        description: 'Full observability for production workloads.',
        features: [
          'Unlimited services',
          '30-day retention',
          '10M events/day',
          'Anomaly detection',
          'PagerDuty integration',
          'Custom dashboards',
        ],
        cta: 'Try Pro',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Dedicated cluster with compliance controls.',
        features: ['Unlimited retention', 'HIPAA/SOC2 compliance', 'Private cloud', 'SRE support'],
        cta: 'Talk to sales',
      },
    ],
  },
  {
    id: 'd-3',
    slug: 'seedenv',
    name: 'SeedEnv',
    tagline: 'Manage secrets and environment variables at scale.',
    description:
      'SeedEnv is a secrets management platform that replaces scattered .env files with a centralized, audited, and access-controlled vault. Supports dynamic secrets, automatic rotation, and native integrations with Vercel, Railway, AWS, and Kubernetes.',
    category: 'DevTools',
    categorySlug: 'devtools',
    tags: ['secrets', 'env-vars', 'security', 'devops'],
    logoPlaceholder: { initials: 'SE', color: '#0284c7' },
    featured: false,
    rating: 4.4,
    reviewCount: 671,
    website: 'https://example.com/seedenv',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Up to 3 projects for individuals.',
        features: ['3 projects', '50 secrets', 'Basic access control'],
        cta: 'Get started',
      },
      {
        name: 'Pro',
        price: 29,
        billingPeriod: 'month',
        description: 'Unlimited secrets with audit logging.',
        features: [
          'Unlimited projects',
          'Unlimited secrets',
          'Audit logs',
          'Secret rotation',
          'Team ACLs',
          'CLI tool',
        ],
        cta: 'Start Pro trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'HSM-backed secrets with compliance certifications.',
        features: ['HSM storage', 'SOC2 Type II', 'SCIM', 'Custom retention'],
        cta: 'Contact security team',
      },
    ],
  },
  {
    id: 'd-4',
    slug: 'reviewhub',
    name: 'ReviewHub',
    tagline: 'Async code review that doesn\'t slow you down.',
    description:
      'ReviewHub layers structured review workflows on top of your existing Git platform. Reviewers get AI-powered diff summaries, inline comment threads with resolution tracking, and automated reviewer assignment based on ownership maps. Cuts PR cycle time by an average of 40%.',
    category: 'DevTools',
    categorySlug: 'devtools',
    tags: ['code-review', 'pull-requests', 'git', 'developer-experience'],
    logoPlaceholder: { initials: 'RH', color: '#0369a1' },
    featured: true,
    rating: 4.5,
    reviewCount: 512,
    website: 'https://example.com/reviewhub',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'For small open-source teams.',
        features: ['5 users', 'Public repos', 'Basic review flows'],
        cta: 'Start free',
      },
      {
        name: 'Pro',
        price: 15,
        billingPeriod: 'month',
        description: 'AI-powered reviews for professional teams.',
        features: [
          'Unlimited users',
          'Private repos',
          'AI diff summaries',
          'Ownership maps',
          'Review analytics',
        ],
        cta: 'Try for free',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Enterprise security and on-premise deployment.',
        features: ['On-premise', 'SSO', 'Compliance', 'SLA'],
        cta: 'Talk to sales',
      },
    ],
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: 'a-1',
    slug: 'lumiq',
    name: 'Lumiq',
    tagline: 'Self-serve analytics every business team can use.',
    description:
      'Lumiq democratizes data analysis with a no-code query builder that translates business questions into SQL, runs against your data warehouse, and renders beautiful charts — all without touching a notebook. Connects to Snowflake, BigQuery, Redshift, and dbt Cloud in minutes.',
    category: 'Analytics',
    categorySlug: 'analytics',
    tags: ['analytics', 'BI', 'no-code', 'data-warehouse', 'SQL'],
    logoPlaceholder: { initials: 'LQ', color: '#f59e0b' },
    featured: true,
    rating: 4.7,
    reviewCount: 1563,
    website: 'https://example.com/lumiq',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Explore your data with no commitment.',
        features: ['1 data source', '3 dashboards', '100 queries/mo', 'CSV export'],
        cta: 'Start for free',
      },
      {
        name: 'Pro',
        price: 89,
        billingPeriod: 'month',
        description: 'Unlimited analytics for data-driven teams.',
        features: [
          'Unlimited data sources',
          'Unlimited dashboards',
          'Scheduled reports',
          'Slack/email delivery',
          'Row-level security',
          'API access',
        ],
        cta: 'Start Pro trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Enterprise data governance and scale.',
        features: ['Column-level security', 'Audit trails', 'Embedded analytics', 'Dedicated infra'],
        cta: 'Talk to data team',
      },
    ],
  },
  {
    id: 'a-2',
    slug: 'trackly',
    name: 'Trackly',
    tagline: 'Product analytics with zero sampling.',
    description:
      'Trackly captures every user action, never samples, and retains data forever on your own infrastructure. Privacy-first by design — GDPR compliant with built-in consent management. Features funnel analysis, retention curves, and cohort breakdowns with SQL-level access.',
    category: 'Analytics',
    categorySlug: 'analytics',
    tags: ['product-analytics', 'user-tracking', 'GDPR', 'funnels', 'retention'],
    logoPlaceholder: { initials: 'TL', color: '#d97706' },
    featured: true,
    rating: 4.5,
    reviewCount: 821,
    website: 'https://example.com/trackly',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'For early-stage products.',
        features: ['1M events/mo', '1 year retention', 'Core analytics', 'GDPR tools'],
        cta: 'Get started',
      },
      {
        name: 'Pro',
        price: 120,
        billingPeriod: 'month',
        description: 'Full-featured analytics for scaling products.',
        features: [
          '20M events/mo',
          'Unlimited retention',
          'Cohort analysis',
          'A/B testing',
          'Webhooks',
          'SQL access',
        ],
        cta: 'Start trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Self-hosted analytics with enterprise SLA.',
        features: ['Self-hosted', 'Unlimited events', 'SOC2', 'Dedicated support'],
        cta: 'Contact us',
      },
    ],
  },
  {
    id: 'a-3',
    slug: 'pulseboard',
    name: 'PulseBoard',
    tagline: 'Revenue analytics for SaaS founders.',
    description:
      'PulseBoard is the MRR dashboard SaaS founders actually want. It syncs with Stripe, Paddle, and Chargebee to give you real-time visibility into MRR, ARR, churn, LTV, and expansion revenue — all broken down by cohort, plan, and geography. No SQL required.',
    category: 'Analytics',
    categorySlug: 'analytics',
    tags: ['revenue-analytics', 'MRR', 'SaaS-metrics', 'Stripe', 'churn'],
    logoPlaceholder: { initials: 'PB', color: '#b45309' },
    featured: true,
    rating: 4.8,
    reviewCount: 706,
    website: 'https://example.com/pulseboard',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Up to $10k MRR tracked for free.',
        features: ['$10k MRR cap', '1 payment integration', 'Core metrics', '90-day history'],
        cta: 'Connect Stripe',
      },
      {
        name: 'Pro',
        price: 49,
        billingPeriod: 'month',
        description: 'Unlimited revenue tracking for growing SaaS.',
        features: [
          'Unlimited MRR',
          '3 payment integrations',
          'Cohort analysis',
          'Forecasting',
          'Custom reports',
          'Slack alerts',
        ],
        cta: 'Start Pro trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Multi-product, multi-currency at scale.',
        features: ['Multi-brand', 'FP&A export', 'SSO', 'Dedicated analyst'],
        cta: 'Talk to sales',
      },
    ],
  },
  {
    id: 'a-4',
    slug: 'segflow',
    name: 'SegFlow',
    tagline: 'Customer data pipelines, simplified.',
    description:
      'SegFlow is a customer data platform (CDP) that unifies data from hundreds of sources into clean, enriched customer profiles. Build dynamic segments, trigger cross-channel journeys, and sync audiences to your ad platforms, CRM, and data warehouse — all with a visual no-code interface.',
    category: 'Analytics',
    categorySlug: 'analytics',
    tags: ['CDP', 'data-pipelines', 'segmentation', 'customer-data', 'ETL'],
    logoPlaceholder: { initials: 'SF', color: '#92400e' },
    featured: false,
    rating: 4.3,
    reviewCount: 489,
    website: 'https://example.com/segflow',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'For early-stage companies getting started with CDP.',
        features: ['1,000 MTUs', '5 sources', '2 destinations', 'Core segments'],
        cta: 'Get started',
      },
      {
        name: 'Pro',
        price: 199,
        billingPeriod: 'month',
        description: 'Full CDP capabilities for mid-market teams.',
        features: [
          '25,000 MTUs',
          'Unlimited sources',
          '10 destinations',
          'Journey builder',
          'Identity resolution',
          'Predictive traits',
        ],
        cta: 'Start trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Enterprise-scale CDP with data residency options.',
        features: ['Unlimited MTUs', 'Data residency', 'HIPAA', 'Dedicated support'],
        cta: 'Talk to sales',
      },
    ],
  },

  // ── CRM ───────────────────────────────────────────────────────────────────
  {
    id: 'c-1',
    slug: 'dealpath',
    name: 'DealPath',
    tagline: 'The CRM that closes deals, not just tracks them.',
    description:
      'DealPath is a sales CRM built for B2B teams that hate data entry. Its AI copilot auto-logs calls and emails, drafts follow-up sequences, and surfaces deals at risk before they fall through the cracks. Native integrations with Gmail, Outlook, LinkedIn, and Zoom.',
    category: 'CRM',
    categorySlug: 'crm',
    tags: ['CRM', 'sales', 'AI', 'pipeline', 'automation'],
    logoPlaceholder: { initials: 'DP', color: '#10b981' },
    featured: true,
    rating: 4.6,
    reviewCount: 1892,
    website: 'https://example.com/dealpath',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'CRM essentials for solo sellers.',
        features: ['1 user', '250 contacts', 'Email integration', 'Basic pipeline'],
        cta: 'Start for free',
      },
      {
        name: 'Pro',
        price: 55,
        billingPeriod: 'month',
        description: 'AI-powered selling for growing sales teams.',
        features: [
          'Unlimited users',
          'Unlimited contacts',
          'AI call logging',
          'Email sequences',
          'Deal scoring',
          'Forecasting',
        ],
        cta: 'Start 14-day trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Revenue operations for enterprise sales orgs.',
        features: ['Custom fields', 'Territory management', 'Advanced analytics', 'SSO', 'API'],
        cta: 'Talk to sales',
      },
    ],
  },
  {
    id: 'c-2',
    slug: 'supportiq',
    name: 'SupportIQ',
    tagline: 'Customer support that learns from every ticket.',
    description:
      'SupportIQ is a helpdesk platform powered by an AI layer trained on your own product documentation and past tickets. It auto-resolves up to 60% of support requests, drafts responses for agents, and identifies recurring issues to feed back to your product team.',
    category: 'CRM',
    categorySlug: 'crm',
    tags: ['support', 'helpdesk', 'AI', 'customer-success', 'ticketing'],
    logoPlaceholder: { initials: 'SI', color: '#059669' },
    featured: true,
    rating: 4.4,
    reviewCount: 734,
    website: 'https://example.com/supportiq',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Basic support desk for early-stage products.',
        features: ['2 agents', '100 tickets/mo', 'Email channel', 'Knowledge base'],
        cta: 'Get started',
      },
      {
        name: 'Pro',
        price: 39,
        billingPeriod: 'month',
        description: 'AI-assisted support for scaling teams.',
        features: [
          'Unlimited agents',
          'Unlimited tickets',
          'AI auto-reply',
          'Live chat',
          'Ticket analytics',
          'SLA tracking',
        ],
        cta: 'Start trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Enterprise helpdesk with advanced integrations.',
        features: ['Custom AI models', 'SSO', 'CSAT benchmarks', 'Dedicated CSM'],
        cta: 'Contact us',
      },
    ],
  },
  {
    id: 'c-3',
    slug: 'onboardly',
    name: 'Onboardly',
    tagline: 'Customer onboarding that drives time-to-value.',
    description:
      'Onboardly builds interactive product tours, onboarding checklists, and in-app guidance without engineering effort. Customer success teams can create and deploy onboarding flows in hours, then track completion rates and correlate onboarding with retention and expansion metrics.',
    category: 'CRM',
    categorySlug: 'crm',
    tags: ['onboarding', 'customer-success', 'product-tours', 'retention', 'no-code'],
    logoPlaceholder: { initials: 'OL', color: '#34d399' },
    featured: true,
    rating: 4.7,
    reviewCount: 618,
    website: 'https://example.com/onboardly',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Basic onboarding for early products.',
        features: ['1 product tour', 'Up to 100 MAU', 'Basic analytics'],
        cta: 'Start building',
      },
      {
        name: 'Pro',
        price: 99,
        billingPeriod: 'month',
        description: 'Full onboarding suite for growth teams.',
        features: [
          'Unlimited flows',
          '5,000 MAU',
          'Checklists & tooltips',
          'A/B testing',
          'Retention analytics',
          'Zapier integration',
        ],
        cta: 'Start trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Onboarding at scale with custom branding.',
        features: ['Unlimited MAU', 'White-label', 'SSO', 'Custom SLA'],
        cta: 'Talk to sales',
      },
    ],
  },
  {
    id: 'c-4',
    slug: 'churnguard',
    name: 'ChurnGuard',
    tagline: 'Predict and prevent customer churn before it happens.',
    description:
      'ChurnGuard is a churn prediction and prevention platform that analyzes product usage, support patterns, and billing signals to surface at-risk accounts weeks before they churn. CS teams get actionable playbooks and automated outreach triggers to intervene at the right moment.',
    category: 'CRM',
    categorySlug: 'crm',
    tags: ['churn', 'customer-success', 'predictive', 'health-scores', 'retention'],
    logoPlaceholder: { initials: 'CG', color: '#6ee7b7' },
    featured: false,
    rating: 4.5,
    reviewCount: 381,
    website: 'https://example.com/churnguard',
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        billingPeriod: 'month',
        description: 'Basic health scoring for small accounts.',
        features: ['Up to 50 accounts', 'Basic health scores', '1 data source'],
        cta: 'Get started',
      },
      {
        name: 'Pro',
        price: 149,
        billingPeriod: 'month',
        description: 'Predictive churn with automated playbooks.',
        features: [
          'Unlimited accounts',
          'AI churn prediction',
          'Automated playbooks',
          'Outreach triggers',
          'CS team dashboard',
          'Salesforce sync',
        ],
        cta: 'Start trial',
        highlighted: true,
      },
      {
        name: 'Enterprise',
        price: null,
        billingPeriod: 'custom',
        description: 'Enterprise CS operations at scale.',
        features: ['Custom ML models', 'Advanced segmentation', 'SSO', 'Dedicated CS strategist'],
        cta: 'Talk to sales',
      },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: CategorySlug): Product[] {
  return PRODUCTS.filter((p) => p.categorySlug === categorySlug);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}

export function getCategoryBySlug(slug: string): CategoryMeta | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}


